-- SMODS.Sticker {
--     key = 'ferureward',
--     rate = 0,
--     badge_colour = HEX('1b1a55'),
--     default_compat = false,
--     sets = {
--         Default = true
--     },
--     atlas = 'CustomStickers',
--     pos = { x = 0, y = 0 },
--     set_sticker = function(self, card, val)
--         card.ability[self.key] = val
--     end,
-- }