-- SMODS.Consumable {
--     key = 'loop',
--     set = 'rune',
--     pos = { x = 0, y = 1 },
--     config = { extra = {
--     } },
--     cost = 10,
--     unlocked = true,
--     discovered = true,
--     hidden = false,
--     can_repeat_soul = false,
--     atlas = 'CustomConsumables',
--     can_use = function(self, card)
--         return true
--     end,
--     loc_vars = function(self, info_queue, card)
--         return { vars = { G.GAME.maxboism_incremental_points or 0, G.GAME.maxboism_incremental_click or 1 } }
--     end,
--     calculate = function(self, card, context)

--     end,
--     use = function(self, card, area, copier)
--         local used_card = card or copier

--         if not G.GAME.maxboism_pseudo_open_active then
--             if G.GAME.maxboism_incremental_points then
--                 G.GAME.maxboism_incremental_points = G.GAME.maxboism_incremental_points + 
--                 G.GAME.maxboism_incremental_click
--             else
--                 G.GAME.maxboism_incremental_points = 1
--                 G.GAME.maxboism_incremental_click = 1
--                 G.GAME.maxboism_incremental_extra = 1
--             end

--             if G.GAME.maxboism_incremental_points >= 5 and not G.GAME.maxboism_incremental_first_shop then
--                 G.GAME.maxboism_incremental_first_shop = true
--                 G.GAME.maxboism_incremental_extra = 2
--                 G.GAME.maxboism_incremental_upgrade1_price = 5
--             end


--             used_card:pseudo_open({
--                 draw_hand = false,
--                 choose = 1,
--                 extra = G.GAME.maxboism_incremental_extra,
--                 background_color = { HEX('b22e2e'), HEX('6b2009') },
--                 create_card = function(
--                     self, card, i)
--                     local _card = nil
--                     if i == 1 then
--                         _card = SMODS.create_card({ area = G.pack_cards, key = "c_maxboism_loop", skip_materialize = true })
--                     elseif i == 2 then
--                         _card = SMODS.create_card({ area = G.pack_cards, key = "c_maxboism_inc_shop1-1", skip_materialize = true })
--                     end
--                     return _card
--                 end,
--             })
--         end
--     end,
-- }
